### ISSUE TITLE
defining Transportation

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/process#9]
Let's start with transportation of physical resources.
1. Do we have a use case we can start working with? @bhaugen 
2. If we want to transport 1000kg of apples, already packed in 50kg wooden crates. How do we connect that resource with transport? I don't think it goes as neither the input or output... (let's maybe pick a use case and let it drive our work)

**Comment by ahdinosaur** [comment]
strawperson for transferring apples:

```yml
'@type': vf:Transportation
resource: ex:resource/those-delicious-crates-of-apples-i-got-while-dumpster-diving
dimension: 20
start: ex:locations/the-zig-zag
end: ex:locations/the-lowlands
process:
  '@type': vf:Process
  inputs:
    - '@type': vf:Consume
      resource: ex:resources/coop-petrol
      dimension: 1 L
    - '@type': vf:Use
      resource: ex:resource/coop-vehicle
      dimension: 1
```

where vf:Transportation is not a process but instead has one process.

versus i think the current approach in NRP is the process returns a transportation service which describes the location change?
